### ISSUE TITLE
Make rendering a view easier.

### ISSUE THREAD

**Issue by noone-crypto** [cold-php/coldphp#1]
Well, I was developing a blog, and I noticed that to render a view I need to create the blade engine in:
**App\Controllers\Controller->Render::create ()**,

I think it would be more practical to create a helper to return a view

About the configuration parameters [template path, compile path, mode], they would be easier in:
**config>blade.php**

**_I am willing to open a pull-request_**

**Comment by danielspinard** [comment]
Hi, grateful for the feedback, we're working on it right now!
